doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                addtime: App\Doctrine\AddTime
                convert_tz: App\Doctrine\ConvertTz
                date: App\Doctrine\Date
                date_format: App\Doctrine\DateFormat
                dateadd: App\Doctrine\DateAdd
                datesub: App\Doctrine\DateSub
                datediff: App\Doctrine\DateDiff
                day: App\Doctrine\Day
                dayname: App\Doctrine\DayName
                dayofweek: App\Doctrine\DayOfWeek
                dayofyear: App\Doctrine\DayOfYear
                div: App\Doctrine\Div
                from_unixtime: App\Doctrine\FromUnixtime
                hour: App\Doctrine\Hour
                last_day: App\Doctrine\LastDay
                makedate: App\Doctrine\MakeDate
                minute: App\Doctrine\Minute
                now: App\Doctrine\Now
                month: App\Doctrine\Month
                monthname: App\Doctrine\MonthName
                period_diff: App\Doctrine\PeriodDiff
                second: App\Doctrine\Second
                sectotime: App\Doctrine\SecToTime
                strtodate: App\Doctrine\StrToDate
                time: App\Doctrine\Time
                timediff: App\Doctrine\TimeDiff
                timestampadd: App\Doctrine\TimestampAdd
                timestampdiff: App\Doctrine\TimestampDiff
                timetosec: App\Doctrine\TimeToSec
                week: App\Doctrine\Week
                weekday: App\Doctrine\WeekDay
                year: App\Doctrine\Year
                yearmonth: App\Doctrine\YearMonth
                yearweek: App\Doctrine\YearWeek
                unix_timestamp: App\Doctrine\UnixTimestamp
                utc_timestamp: App\Doctrine\UtcTimestamp
                extract: App\Doctrine\Extract
            numeric_functions:
                acos: App\Doctrine\Acos
                asin: App\Doctrine\Asin
                atan2: App\Doctrine\Atan2
                atan: App\Doctrine\Atan
                bit_count: App\Doctrine\BitCount
                bit_xor: App\Doctrine\BitXor
                ceil: App\Doctrine\Ceil
                cos: App\Doctrine\Cos
                cot: App\Doctrine\Cot
                degrees: App\Doctrine\Degrees
                exp: App\Doctrine\Exp
                floor: App\Doctrine\Floor
                log: App\Doctrine\Log
                log10: App\Doctrine\Log10
                log2: App\Doctrine\Log2
                pi: App\Doctrine\Pi
                power: App\Doctrine\Power
                quarter: App\Doctrine\Quarter
                radians: App\Doctrine\Radians
                rand: App\Doctrine\Rand
                round: App\Doctrine\Round
                stddev: App\Doctrine\StdDev
                sin: App\Doctrine\Sin
                std: App\Doctrine\Std
                tan: App\Doctrine\Tan
                variance: App\Doctrine\Variance
            string_functions:
                JSON_ARRAY: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArray
                JSON_ARRAY_APPEND: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArrayAppend
                JSON_ARRAY_INSERT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArrayInsert
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                JSON_CONTAINS_PATH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContainsPath
                JSON_DEPTH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonDepth
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_INSERT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonInsert
                JSON_KEYS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonKeys
                JSON_LENGTH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonLength
                JSON_MERGE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonMerge
                JSON_MERGE_PATCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonMergePatch
                JSON_OBJECT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonObject
                JSON_QUOTE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonQuote
                JSON_REMOVE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonRemove
                JSON_REPLACE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonReplace
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                JSON_SET: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSet
                JSON_TYPE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonType
                JSON_UNQUOTE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote
                JSON_VALID: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonValid
                aes_decrypt: App\Doctrine\AesDecrypt
                aes_encrypt: App\Doctrine\AesEncrypt
                any_value: App\Doctrine\AnyValue
                ascii: App\Doctrine\Ascii
                binary: App\Doctrine\Binary
                cast: App\Doctrine\Cast
                char_length: App\Doctrine\CharLength
                collate: App\Doctrine\Collate
                concat_ws: App\Doctrine\ConcatWs
                countif: App\Doctrine\CountIf
                crc32: App\Doctrine\Crc32
                degrees: App\Doctrine\Degrees
                field: App\Doctrine\Field
                find_in_set: App\Doctrine\FindInSet
                format: App\Doctrine\Format
                greatest: App\Doctrine\Greatest
                group_concat: App\Doctrine\GroupConcat
                hex: App\Doctrine\Hex
                ifelse: App\Doctrine\IfElse
                ifnull: App\Doctrine\IfNull
                inet_aton: App\Doctrine\InetAton
                inet_ntoa: App\Doctrine\InetNtoa
                inet6_aton: App\Doctrine\Inet6Aton
                inet6_ntoa: App\Doctrine\Inet6Ntoa
                instr: App\Doctrine\Instr
                is_ipv4: App\Doctrine\IsIpv4
                is_ipv4_compat: App\Doctrine\IsIpv4Compat
                is_ipv4_mapped: App\Doctrine\IsIpv4Mapped
                is_ipv6: App\Doctrine\IsIpv6
                lag: App\Doctrine\Lag
                lead: App\Doctrine\Lead
                least: App\Doctrine\Least
                lpad: App\Doctrine\Lpad
                match: App\Doctrine\MatchAgainst
                md5: App\Doctrine\Md5
                nullif: App\Doctrine\NullIf
                over: App\Doctrine\Over
                radians: App\Doctrine\Radians
                regexp: App\Doctrine\Regexp
                replace: App\Doctrine\Replace
                rpad: App\Doctrine\Rpad
                sha1: App\Doctrine\Sha1
                sha2: App\Doctrine\Sha2
                soundex: App\Doctrine\Soundex
                str_to_date: App\Doctrine\StrToDate
                substring_index: App\Doctrine\SubstringIndex
                unhex: App\Doctrine\Unhex
                uuid_short: App\Doctrine\UuidShort
                