yasin:
    label: Yasin
    tabs: {  }
franck:
    label: Franck
    tabs: [{ label: '', type: radio, help: '', slug: '', option: { label: Homme, value: H } }, { label: '', type: radio, help: '', slug: '', option: { label: Homme, value: H } }, { label: '', type: radio, help: '', slug: '', option: { label: Homme, value: H } }, { label: '', type: radio, help: '', slug: '', option: { label: Homme, value: H } }]
